services:
  # PHP service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aleph-app
    working_dir: /var/www/aleph-laravel
    env_file:
      - .env
    environment:
      DB_DATABASE: aleph
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - .:/var/www
    networks:
      - laravel
    expose:
      - "9000"

  # MySQL service
  mysql:
    image: mysql:8.0
    container_name: aleph-mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: aleph
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER} 
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  # Nginx service
  webserver:
    image: nginx:alpine
    container_name: aleph-webserver
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

  # Mailhog service
  mailhog:
    image: mailhog/mailhog
    container_name: aleph-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - laravel

  # PhpMyAdmin service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: aleph-phpmyadmin
    env_file:
      - .env
    environment:
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_HOST: mysql
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:
  esdata: